import { useEffect, useState, type FormEvent } from 'react';
import { useOutletContext } from 'react-router-dom';
import { ArrowRightLeft, Landmark, Plus, WalletCards } from 'lucide-react';
import { api, ApiError } from '../api';
import { useApp } from '../context/AppContext';
import type { ShellContext } from '../components/Shell';
import type { Account } from '../types';
import { EmptyState, ErrorState, formatDate, formatMoney, Loading, Modal } from '../components/ui';
import { PageHeading } from './DashboardPage';

export function AccountsPage() {
  const { selectedProfileId } = useApp(); const { openTransaction, refreshKey, refresh } = useOutletContext<ShellContext>(); const [items, setItems] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false);
  const load = () => { if (!selectedProfileId) return setLoading(false); setLoading(true); api<Account[]>(`/profiles/${selectedProfileId}/accounts`).then(setItems).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); };
  useEffect(load, [selectedProfileId, refreshKey]);
  if (!selectedProfileId) return <div className="page"><EmptyState title="Choose a profile" message="Accounts are kept separate within each financial profile."/></div>;
  const total = items.reduce((sum, item) => sum + Number(item.balance), 0); const available = items.filter((item) => item.includeInAvailableCash).reduce((sum, item) => sum + Number(item.balance), 0);
  return <div className="page"><PageHeading eyebrow="Where the money lives" title="Accounts" subtitle="Balances are calculated directly from posted journal lines." actions={<div className="heading-actions"><button className="button secondary" onClick={() => openTransaction('TRANSFER')}><ArrowRightLeft/> Transfer</button><button className="button primary" onClick={() => setShowForm(true)}><Plus/> Add account</button></div>}/><div className="account-totals"><div><span>Total account balance</span><strong>{formatMoney(total)}</strong></div><div><span>Available cash</span><strong>{formatMoney(available)}</strong></div><small>{items.length} active account{items.length === 1 ? '' : 's'}</small></div>{loading ? <Loading label="Loading accounts"/> : error ? <ErrorState message={error} retry={load}/> : items.length ? <div className="account-grid">{items.map((account) => <article className="account-card" key={account.id}><div className="account-card-head"><span className="account-icon"><Landmark/></span><span className="status status-active">active</span></div><div><small>{account.type.toLowerCase().replaceAll('_', ' ')}</small><h3>{account.name}</h3><p>{account.institution || 'Independent account'}</p></div><strong>{formatMoney(account.balance, account.currencyCode)}</strong><div className="account-movement"><span><small>In this month</small><b className="positive">+{formatMoney(account.monthlyInflow, account.currencyCode)}</b></span><span><small>Out this month</small><b>−{formatMoney(account.monthlyOutflow, account.currencyCode)}</b></span></div><footer>Last activity {account.lastActivity ? formatDate(account.lastActivity) : '—'}</footer></article>)}</div> : <EmptyState icon={<WalletCards/>} title="No accounts yet" message="Create an account to begin tracking money." action={<button className="button primary" onClick={() => setShowForm(true)}><Plus/> Add account</button>}/>} {showForm && <AccountForm profileId={selectedProfileId} onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); refresh(); }}/>}</div>;
}

function AccountForm({ profileId, onClose, onCreated }: { profileId: string; onClose: () => void; onCreated: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await api(`/profiles/${profileId}/accounts`, { method: 'POST', body: JSON.stringify({ name: data.get('name'), type: data.get('type'), institution: data.get('institution') || undefined, currencyCode: 'UGX', openingBalance: Number(data.get('openingBalance') || 0), openingBalanceDate: data.get('openingBalanceDate') || undefined, includeInAvailableCash: data.get('includeInAvailableCash') === 'on', includeInNetWorth: data.get('includeInNetWorth') === 'on', notes: data.get('notes') || undefined }) }); onCreated(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not create the account.'); } finally { setBusy(false); } };
  return <Modal title="Add an account" description="Where does this money live?" onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<label><span>Account name</span><input name="name" placeholder="e.g. Stanbic Bank" required autoFocus/></label><div className="form-grid"><label><span>Account type</span><select name="type" defaultValue="BANK"><option value="BANK">Bank</option><option value="MOBILE_MONEY">Mobile Money</option><option value="CASH">Cash</option><option value="SAVINGS">Savings</option><option value="CREDIT_CARD">Credit Card</option><option value="INVESTMENT">Investment</option><option value="PETTY_CASH">Petty Cash</option><option value="LOAN">Loan</option><option value="OTHER">Other</option></select></label><label><span>Institution</span><input name="institution" placeholder="Optional"/></label><label><span>Opening balance</span><input name="openingBalance" type="number" min="0" step="1" defaultValue="0"/></label><label><span>Balance date</span><input name="openingBalanceDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)}/></label></div><label className="check-row"><input name="includeInAvailableCash" type="checkbox" defaultChecked/><span><strong>Include in available cash</strong><small>Shown in the amount available now</small></span></label><label className="check-row"><input name="includeInNetWorth" type="checkbox" defaultChecked/><span><strong>Include in net worth</strong><small>Count this account in the overall position</small></span></label><footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Creating…' : 'Create account'}</button></footer></form></Modal>;
}
