import { useEffect, useState, type FormEvent } from 'react';
import { Building2, Car, Gem, Plus, Tractor } from 'lucide-react';
import { api, ApiError } from '../api';
import { useApp } from '../context/AppContext';
import { EmptyState, ErrorState, formatDate, formatMoney, Loading, Modal } from '../components/ui';
import { PageHeading } from './DashboardPage';

type Asset = { id: string; name: string; assetType: string; purchaseValue: string; currentEstimatedValue: string; valuationDate: string; description?: string };
const AssetIcon = ({ type }: { type: string }) => type.toLowerCase().includes('vehicle') ? <Car/> : type.toLowerCase().includes('equipment') ? <Tractor/> : type.toLowerCase().includes('property') || type.toLowerCase().includes('land') ? <Building2/> : <Gem/>;

export function AssetsPage() {
  const { selectedProfileId } = useApp(); const [items, setItems] = useState<Asset[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(false); const [version, setVersion] = useState(0);
  const load = () => { if (!selectedProfileId) return setLoading(false); setLoading(true); api<Asset[]>(`/profiles/${selectedProfileId}/assets`).then(setItems).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); };
  useEffect(load, [selectedProfileId, version]);
  if (!selectedProfileId) return <div className="page"><EmptyState title="Choose a profile" message="Assets are owned by a specific financial profile."/></div>;
  const total = items.reduce((sum, item) => sum + Number(item.currentEstimatedValue), 0);
  return <div className="page"><PageHeading eyebrow="What this profile owns" title="Assets" subtitle="Track valuable items and their latest estimated value." actions={<button className="button primary" onClick={() => setForm(true)}><Plus/> Add asset</button>}/><div className="account-totals"><div><span>Total asset value</span><strong>{formatMoney(total)}</strong></div><small>{items.length} active asset{items.length === 1 ? '' : 's'} included in this view</small></div>{loading ? <Loading label="Loading assets"/> : error ? <ErrorState message={error} retry={load}/> : items.length ? <div className="asset-grid">{items.map((asset) => { const change = Number(asset.currentEstimatedValue) - Number(asset.purchaseValue); return <article className="asset-card" key={asset.id}><div className="asset-visual"><AssetIcon type={asset.assetType}/><span>{asset.assetType}</span></div><div className="asset-body"><small>Current estimated value</small><strong>{formatMoney(asset.currentEstimatedValue)}</strong><h3>{asset.name}</h3><p>Valued {formatDate(asset.valuationDate)}</p><div><span>Purchase value <b>{formatMoney(asset.purchaseValue)}</b></span><span>Change <b className={change >= 0 ? 'positive' : 'negative'}>{change >= 0 ? '+' : ''}{formatMoney(change)}</b></span></div></div></article>; })}</div> : <EmptyState icon={<Gem/>} title="No assets yet" message="Add property, vehicles, equipment, investments, or other valuable things." action={<button className="button primary" onClick={() => setForm(true)}><Plus/> Add asset</button>}/>} {form && <AssetForm profileId={selectedProfileId} onClose={() => setForm(false)} onCreated={() => { setForm(false); setVersion((value) => value + 1); }}/>}</div>;
}

function AssetForm({ profileId, onClose, onCreated }: { profileId: string; onClose: () => void; onCreated: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await api(`/profiles/${profileId}/assets`, { method: 'POST', body: JSON.stringify({ name: data.get('name'), assetType: data.get('assetType'), purchaseDate: data.get('purchaseDate') || undefined, purchaseValue: Number(data.get('purchaseValue') || 0), currentEstimatedValue: Number(data.get('currentEstimatedValue')), valuationDate: data.get('valuationDate'), description: data.get('description') || undefined, includeInNetWorth: true }) }); onCreated(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not create this asset.'); } finally { setBusy(false); } };
  return <Modal title="Add an asset" description="Record the latest useful value; it can be updated later." onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<label><span>Asset name</span><input name="name" placeholder="e.g. Farm tractor" required autoFocus/></label><div className="form-grid"><label><span>Asset type</span><select name="assetType"><option>Property</option><option>Land</option><option>Vehicle</option><option>Equipment</option><option>Livestock</option><option>Investment</option><option>Shares</option><option>Other</option></select></label><label><span>Purchase date</span><input name="purchaseDate" type="date"/></label><label><span>Purchase value</span><input name="purchaseValue" type="number" min="0" defaultValue="0"/></label><label><span>Current estimated value</span><input name="currentEstimatedValue" type="number" min="0" required/></label><label><span>Valuation date</span><input name="valuationDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required/></label></div><label><span>Description</span><textarea name="description" rows={3}/></label><footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Add asset'}</button></footer></form></Modal>;
}

