import { useEffect, useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownLeft, ArrowRight, ArrowRightLeft, ArrowUpRight, CalendarClock, CircleAlert, Landmark, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { api } from '../api';
import { useApp } from '../context/AppContext';
import type { DashboardData, Transaction } from '../types';
import type { ShellContext } from '../components/Shell';
import { EmptyState, ErrorState, formatDate, formatMoney, Loading, StatusBadge } from '../components/ui';

type AllData = { profiles: { id: string; name: string; type: string; currency: string; metrics: Record<string, string> }[]; metrics: Record<string, number> };

export function DashboardPage() {
  const { selectedProfileId, selectedProfile } = useApp(); const { openTransaction, refreshKey } = useOutletContext<ShellContext>();
  const [data, setData] = useState<DashboardData | null>(null); const [all, setAll] = useState<AllData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); (selectedProfileId ? api<DashboardData>(`/profiles/${selectedProfileId}/dashboard`).then((result) => { setData(result); setAll(null); }) : api<AllData>('/dashboard/all').then((result) => { setAll(result); setData(null); })).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); };
  useEffect(load, [selectedProfileId, refreshKey]);
  const chartData = useMemo(() => {
    const groups = new Map<string, { name: string; income: number; spending: number }>();
    for (const transaction of [...(data?.recentTransactions ?? [])].reverse()) {
      const name = new Intl.DateTimeFormat('en-UG', { day: 'numeric', month: 'short' }).format(new Date(transaction.transactionDate)); const row = groups.get(name) ?? { name, income: 0, spending: 0 };
      if (transaction.type === 'MONEY_IN') row.income += Number(transaction.amount); if (transaction.type === 'MONEY_OUT') row.spending += Number(transaction.amount); groups.set(name, row);
    }
    return [...groups.values()];
  }, [data]);
  if (loading) return <Loading/>; if (error) return <ErrorState message={error} retry={load}/>;
  if (!selectedProfileId && all) return <div className="page"><PageHeading eyebrow="Consolidated view" title="All Profiles" subtitle="A calm overview across every financial entity."/><div className="metric-grid"><Metric title="Available now" value={formatMoney(all.metrics.available)} icon={<WalletCards/>}/><Metric title="Money in" value={formatMoney(all.metrics.moneyIn)} trend="Across all profiles" icon={<TrendingUp/>}/><Metric title="Money out" value={formatMoney(all.metrics.moneyOut)} icon={<TrendingDown/>}/><Metric title="Combined net worth" value={formatMoney(all.metrics.netWorth)} icon={<Landmark/>}/></div><section><div className="section-heading"><div><p className="eyebrow">Profiles</p><h2>Where your money lives</h2></div></div><div className="profile-summary-grid">{all.profiles.map((profile) => <article className="profile-summary" key={profile.id}><div className="account-icon">{profile.name.charAt(0)}</div><div><span>{profile.type.toLowerCase()}</span><h3>{profile.name}</h3></div><strong>{formatMoney(profile.metrics.available, profile.currency)}</strong><small>Available balance</small><div className="profile-summary-foot"><span>Net cash flow</span><b>{formatMoney(profile.metrics.netCashFlow, profile.currency)}</b></div></article>)}</div></section></div>;
  if (!data || !selectedProfile) return <EmptyState title="Create your first profile" message="A profile keeps one set of finances independent from the rest."/>;
  return <div className="page">
    <PageHeading eyebrow={`${selectedProfile.type.toLowerCase()} profile`} title={`Good morning, ${data.profile.name}`} subtitle="Here’s the financial picture and what needs your attention today." actions={<div className="quick-actions"><button onClick={() => openTransaction('MONEY_IN')}><ArrowDownLeft/> Money In</button><button onClick={() => openTransaction('MONEY_OUT')}><ArrowUpRight/> Money Out</button><button onClick={() => openTransaction('TRANSFER')}><ArrowRightLeft/> Transfer</button></div>}/>
    <div className="metric-grid"><Metric title="Available now" value={formatMoney(data.metrics.available)} trend="Across cash accounts" icon={<WalletCards/>}/><Metric title="Money in" value={formatMoney(data.metrics.moneyIn)} trend="Posted income" positive icon={<TrendingUp/>}/><Metric title="Money out" value={formatMoney(data.metrics.moneyOut)} trend="Posted spending" icon={<TrendingDown/>}/><Metric title="Net worth" value={formatMoney(data.metrics.netWorth)} trend="Assets minus debts" icon={<Landmark/>}/></div>
    <div className="dashboard-grid"><section className="card chart-card"><div className="section-heading compact"><div><p className="eyebrow">Cash movement</p><h2>Income vs spending</h2></div><span className="date-chip">This month</span></div>{chartData.length ? <ResponsiveContainer width="100%" height={260}><AreaChart data={chartData}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#1b7150" stopOpacity={0.2}/><stop offset="95%" stopColor="#1b7150" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e8eae5"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(value) => formatMoney(Number(value))}/><Area type="monotone" dataKey="income" stroke="#1b7150" fill="url(#income)" strokeWidth={2.5}/><Area type="monotone" dataKey="spending" stroke="#c66a4a" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer> : <EmptyState title="No cash movement yet" message="Post a transaction to start the trend."/>}<div className="chart-legend"><span><i className="green"/>Money in</span><span><i className="terracotta"/>Money out</span></div></section>
      <section className="card attention-card"><div className="section-heading compact"><div><p className="eyebrow">Needs attention</p><h2>Coming up</h2></div><CircleAlert size={20}/></div>{data.upcoming.length ? <div className="upcoming-list">{data.upcoming.map((bill) => <div key={bill.id}><span className="activity-icon warning"><CalendarClock/></span><div><strong>{bill.payee}</strong><small>Due {formatDate(bill.dueDate)}</small></div><b>{formatMoney(bill.amount)}</b></div>)}</div> : <EmptyState title="You’re all caught up" message="No bills require attention."/>}</section></div>
    <div className="dashboard-grid lower"><section className="card activity-card"><div className="section-heading compact"><div><p className="eyebrow">Latest</p><h2>Recent activity</h2></div><a href="/transactions">View all <ArrowRight size={16}/></a></div>{data.recentTransactions.length ? <div className="transaction-list">{data.recentTransactions.slice(0, 6).map((transaction) => <TransactionRow key={transaction.id} transaction={transaction}/>)}</div> : <EmptyState title="No transactions yet" message="Record your first money-in or money-out transaction."/>}</section><section className="card accounts-preview"><div className="section-heading compact"><div><p className="eyebrow">Accounts</p><h2>Balance distribution</h2></div><a href="/accounts">Manage <ArrowRight size={16}/></a></div>{data.accounts.map((account) => <div className="balance-row" key={account.id}><span className="account-icon"><Landmark/></span><div><strong>{account.name}</strong><small>{account.type.toLowerCase().replaceAll('_', ' ')}</small></div><b>{formatMoney(account.balance, account.currencyCode)}</b></div>)}</section></div>
  </div>;
}

export function PageHeading({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions?: React.ReactNode }) { return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{actions}</header>; }
function Metric({ title, value, trend, icon, positive }: { title: string; value: string; trend?: string; icon: React.ReactNode; positive?: boolean }) { return <article className="metric-card"><div><span>{title}</span><i>{icon}</i></div><strong>{value}</strong>{trend && <small className={positive ? 'positive' : ''}>{trend}</small>}</article>; }
export function TransactionRow({ transaction, onClick }: { transaction: Transaction; onClick?: () => void }) {
  const incoming = ['MONEY_IN', 'OPENING_BALANCE', 'OWNER_CONTRIBUTION', 'LOAN_RECEIVED', 'REFUND', 'REIMBURSEMENT'].includes(transaction.type);
  const transfer = transaction.type === 'TRANSFER';
  return <button className="transaction-row" onClick={onClick}><span className={`activity-icon ${incoming ? 'positive' : transfer ? 'neutral' : 'negative'}`}>{incoming ? <ArrowDownLeft/> : transfer ? <ArrowRightLeft/> : <ArrowUpRight/>}</span><div><strong>{transaction.description || transaction.counterparty || transaction.category?.name || transaction.type.replaceAll('_', ' ')}</strong><small>{transaction.toAccount?.name || transaction.fromAccount?.name} · {formatDate(transaction.transactionDate)}</small></div><span className="row-status"><StatusBadge status={transaction.status}/></span><b className={incoming ? 'positive' : transfer ? '' : 'negative'}>{incoming ? '+' : transfer ? '' : '−'}{formatMoney(transaction.amount)}</b></button>;
}
