import { useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2, WalletCards } from 'lucide-react';
import { ApiError } from '../api';
import { useApp } from '../context/AppContext';

export function LoginPage() {
  const { login, setup, setupRequired } = useApp(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { if (setupRequired) await setup(String(data.get('name')), String(data.get('email')), String(data.get('password'))); else await login(String(data.get('email')), String(data.get('password'))); } catch (caught) { setError(caught instanceof ApiError ? caught.message : setupRequired ? 'Unable to create the owner account.' : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <main className="login-page"><section className="login-story"><div className="login-brand"><WalletCards/> Money Manager</div><div><p className="eyebrow light">Your financial command centre</p><h1>Every part of your money, finally in one calm place.</h1><p>Personal finances and every business stay separate, while a rigorous ledger keeps the full picture accurate.</p><ul><li><CheckCircle2/> Know what is available right now</li><li><CheckCircle2/> Capture money in or out in seconds</li><li><CheckCircle2/> See the story behind every balance</li></ul></div><blockquote>“Simple on the surface. Rigorous underneath.”</blockquote></section><section className="login-panel"><form onSubmit={submit}><div className="mobile-login-brand"><WalletCards/> Money Manager</div><p className="eyebrow">{setupRequired ? 'First-time setup' : 'Welcome back'}</p><h2>{setupRequired ? 'Create your owner account' : 'Sign in to your finances'}</h2><p className="muted">{setupRequired ? 'Start with a clean personal profile and no financial activity.' : 'Enter your owner credentials to continue.'}</p>{error && <div className="form-error">{error}</div>}{setupRequired && <label><span>Your name</span><input name="name" autoComplete="name" required/></label>}<label><span>Email address</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Password</span><input name="password" type="password" autoComplete={setupRequired ? 'new-password' : 'current-password'} minLength={setupRequired ? 12 : 8} required/></label><button className="button primary large" disabled={busy}>{busy ? setupRequired ? 'Creating account…' : 'Signing in…' : <>{setupRequired ? 'Create account' : 'Sign in'} <ArrowRight size={18}/></>}</button>{setupRequired && <small className="seed-note">No demo transactions or balances will be added.</small>}</form></section></main>;
}
