import { useEffect, useState } from 'react';
import { Download, FileSpreadsheet, Printer } from 'lucide-react';
import { api } from '../api';
import { useApp } from '../context/AppContext';
import { EmptyState, ErrorState, formatMoney, Loading } from '../components/ui';
import { PageHeading } from './DashboardPage';

type Balance = { id: string; code: string; name: string; accountClass: string; balance: string };
type ProfitLoss = { income: Balance[]; expenses: Balance[]; totalIncome: number; totalExpenses: number };

export function ReportsPage() {
  const { selectedProfileId, selectedProfile } = useApp(); const [report, setReport] = useState('profit-loss'); const [trial, setTrial] = useState<Balance[]>([]); const [profit, setProfit] = useState<ProfitLoss | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { if (!selectedProfileId) return setLoading(false); setLoading(true); Promise.all([api<Balance[]>(`/profiles/${selectedProfileId}/reports/trial-balance`), api<ProfitLoss>(`/profiles/${selectedProfileId}/reports/profit-loss`)]).then(([t, p]) => { setTrial(t); setProfit(p); }).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); }; useEffect(load, [selectedProfileId]);
  if (!selectedProfileId) return <div className="page"><EmptyState title="Choose a profile" message="Select one profile to view its accounting reports. Consolidated reporting is available on Home."/></div>;
  const downloadCsv = () => { const rows = report === 'trial-balance' ? [['Code', 'Account', 'Class', 'Balance'], ...trial.map((item) => [item.code, item.name, item.accountClass, item.balance])] : [['Section', 'Account', 'Amount'], ...(profit?.income ?? []).map((item) => ['Income', item.name, item.balance]), ...(profit?.expenses ?? []).map((item) => ['Expense', item.name, item.balance])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selectedProfile?.name ?? 'profile'}-${report}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="page"><PageHeading eyebrow="Understand the story" title="Reports" subtitle="Accounting reports reconcile directly with posted journal lines." actions={<div className="heading-actions"><button className="button secondary" onClick={() => window.print()}><Printer/> Print</button><button className="button primary" onClick={downloadCsv}><Download/> Export CSV</button></div>}/><div className="report-layout"><aside className="report-nav"><span>Everyday reports</span><button className={report === 'profit-loss' ? 'active' : ''} onClick={() => setReport('profit-loss')}>Money In & Out<small>Profit summary</small></button><button className={report === 'account-balances' ? 'active' : ''} onClick={() => setReport('account-balances')}>Account balances<small>Where money lives</small></button><span>Advanced accounting</span><button className={report === 'trial-balance' ? 'active' : ''} onClick={() => setReport('trial-balance')}>Trial balance<small>Debit and credit position</small></button></aside><section className="card report-card">{loading ? <Loading label="Preparing report"/> : error ? <ErrorState message={error} retry={load}/> : report === 'profit-loss' && profit ? <><ReportHeader title="Money In & Out" subtitle="All posted income and spending"/><div className="report-summary"><div><span>Money in</span><strong className="positive">{formatMoney(profit.totalIncome)}</strong></div><div><span>Money out</span><strong>{formatMoney(profit.totalExpenses)}</strong></div><div><span>Net result</span><strong>{formatMoney(profit.totalIncome - profit.totalExpenses)}</strong></div></div><ReportSection title="Money in" rows={profit.income}/><ReportSection title="Money out" rows={profit.expenses}/></> : report === 'account-balances' ? <><ReportHeader title="Account balances" subtitle="Balances by ledger account"/><ReportSection title="Assets and liabilities" rows={trial.filter((item) => ['ASSET', 'LIABILITY'].includes(item.accountClass))}/></> : <><ReportHeader title="Trial balance" subtitle="All non-zero ledger account balances"/><div className="report-table"><div className="report-table-head"><span>Code</span><span>Account</span><span>Class</span><span>Balance</span></div>{trial.map((item) => <div key={item.id}><span>{item.code}</span><strong>{item.name}</strong><span>{item.accountClass.toLowerCase()}</span><b>{formatMoney(item.balance)}</b></div>)}</div></>}</section></div></div>;
}
function ReportHeader({ title, subtitle }: { title: string; subtitle: string }) { return <header className="report-header"><div><p className="eyebrow">Current position</p><h2>{title}</h2><p>{subtitle}</p></div><FileSpreadsheet/></header>; }
function ReportSection({ title, rows }: { title: string; rows: Balance[] }) { return <div className="report-section"><h3>{title}</h3>{rows.length ? rows.map((item) => <div key={item.id}><span>{item.name}</span><b>{formatMoney(item.balance)}</b></div>) : <p>No posted balances in this section.</p>}<footer><strong>Total {title.toLowerCase()}</strong><b>{formatMoney(rows.reduce((sum, item) => sum + Number(item.balance), 0))}</b></footer></div>; }

