import { useState, type FormEvent } from 'react';
import { Archive, Bell, ChevronRight, Database, Moon, Plus, ShieldCheck, Tags, UserRound, WalletCards } from 'lucide-react';
import { api, ApiError } from '../api';
import { useApp } from '../context/AppContext';
import { Modal } from '../components/ui';
import { PageHeading } from './DashboardPage';

export function SettingsPage() {
  const { profiles, refreshProfiles, selectProfile } = useApp(); const [showForm, setShowForm] = useState(false);
  return <div className="page"><PageHeading eyebrow="Make it yours" title="Settings" subtitle="Manage profiles and the rules behind your financial workspace."/><div className="settings-layout"><section><div className="section-heading"><div><p className="eyebrow">Financial entities</p><h2>Profiles</h2></div><button className="button primary small" onClick={() => setShowForm(true)}><Plus/> Create profile</button></div><div className="settings-profiles">{profiles.map((profile) => <article key={profile.id}><span className="profile-icon">{profile.name.charAt(0)}</span><div><strong>{profile.name}</strong><small>{profile.type.toLowerCase()} · {profile.baseCurrencyCode}</small></div><span className="status status-active">active</span><button className="icon-button" aria-label={`Open ${profile.name}`}><ChevronRight/></button></article>)}</div></section><section><div className="section-heading"><div><p className="eyebrow">Workspace</p><h2>Preferences and data</h2></div></div><div className="settings-list"><Setting icon={<Tags/>} title="Categories" subtitle="Names that map to ledger accounts"/><Setting icon={<WalletCards/>} title="Accounts" subtitle="Cash, bank, mobile money, cards, and more"/><Setting icon={<Bell/>} title="Notifications" subtitle="Bills, budgets, and balance warnings"/><Setting icon={<Moon/>} title="Appearance" subtitle="Light theme · dark-mode ready"/><Setting icon={<Database/>} title="Data import and export" subtitle="CSV imports, backups, and exports"/><Setting icon={<ShieldCheck/>} title="Advanced accounting" subtitle="Chart of accounts, journals, and audit trail"/><Setting icon={<Archive/>} title="Archived records" subtitle="Profiles and accounts kept for history"/></div></section></div>{showForm && <ProfileForm onClose={() => setShowForm(false)} onCreated={async (id) => { await refreshProfiles(); await selectProfile(id); setShowForm(false); }}/>}</div>;
}
function Setting({ icon, title, subtitle }: { icon: React.ReactNode; title: string; subtitle: string }) { return <div className="setting-row">{icon}<div><strong>{title}</strong><small>{subtitle}</small></div></div>; }
function ProfileForm({ onClose, onCreated }: { onClose: () => void; onCreated: (id: string) => Promise<void> }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { const profile = await api<{ id: string }>('/profiles', { method: 'POST', body: JSON.stringify({ name: data.get('name'), type: data.get('type'), description: data.get('description') || undefined, baseCurrencyCode: 'UGX', financialYearStart: Number(data.get('financialYearStart')) }) }); await onCreated(profile.id); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not create this profile.'); } finally { setBusy(false); } }; return <Modal title="Create a profile" description="A separate financial entity with its own accounts and ledger." onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="profile-form-icon"><UserRound/></div><label><span>Profile name</span><input name="name" placeholder="e.g. Island Farm" required autoFocus/></label><div className="form-grid"><label><span>Profile type</span><select name="type" defaultValue="BUSINESS"><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option><option value="INVESTMENT">Investment</option><option value="PROJECT">Project</option><option value="OTHER">Other</option></select></label><label><span>Financial year starts</span><select name="financialYearStart" defaultValue="1">{['January','February','March','April','May','June','July','August','September','October','November','December'].map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select></label></div><label><span>Description</span><textarea name="description" rows={3} placeholder="What does this profile manage?"/></label><div className="integrity-note"><ShieldCheck/><div><strong>A clean ledger is included</strong><p>Money Manager will create a chart of accounts and helpful categories for this profile.</p></div></div><footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Creating…' : 'Create profile'}</button></footer></form></Modal>; }
